---
title: "(Un)employment: The labor market"
subtitle: "Principles of Macroeconomics // Fall 2024"
institute: "marcio.santetti@emerson.edu"
format: 
  clean-revealjs:
    self-contained: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Prof. Santetti
---
  
# Readings {background-color="#62259D"}
  
  
  
## Recommended readings
  
<br>
  
**Required readings**:
  
- [Macroeconomics in Context]{.note}, 4th ed.
  - Chapter ??.


  
<br>

**Recommended watching**:

- &#128279; [[The manipulation of labor markets, by Richard Wolff (*Democracy at Work*)]{.link}](https://www.youtube.com/watch?v=6O5eBz1MsK8)
  
  
## Words of the day
  
<br><br>

  - Labor supply;
  - Labor demand;
  - Bargaining


# The market for labor {background-color="#62259D"}


## The market for labor

<br><br>

  - In a not-too-far future from now, what [characteristics]{.note} will you be seeking in your job? (pay, opportunities, network, fulfillment, benefits, environment)
  
. . .
  
<br>

  - And what will you want to [avoid]{.note}? (long commute, dangerous, repetitive, low pay, lack of benefits)


## The market for labor

First, defining what [markets]{.hi} mean.

. . .

$\hspace{1cm}$ &rarr; [Market]{.note}: an [institution]{.hi-slate} that facilitates economic interactions among *buyers* and *sellers.*

. . .

<br>

However, [labor markets]{.hi-orange} are *different* from other markets in [several]{.note} ways. (a market in which employers interact with people who wish to work)

. . .

<br>

  - What is for [sale]{.note}?
  
  - What is available for [purchase]{.note}?
  
  - Do [interests]{.note} necessarily *match* between all parts involved?




## The market for labor




## The market for labor


## The market for labor

# Next time: ??? {background-color="#62259D"}