---
title: "Macroeconomics & well-being IV"
subtitle: "Principles of Macroeconomics // Fall 2024"
institute: "marcio.santetti@emerson.edu"
format: 
  clean-revealjs:
    self-contained: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Prof. Santetti
---

# Readings {background-color="#62259D"}



## Recommended readings

<br>

**Required readings**:

  - [Macroeconomics in Context]{.note}, 4th ed.
    - Chapter 5.
    
  🔗 [[The trouble with GDP (*The Economist*)]{.link}](https://archive.is/3gIZJ) 
  
  🔗 [[How to measure prosperity (*The Economist*)]{.link}](https://archive.is/nNxuG) 


## The latest numbers

<br><br>

  🔗 [[Gross Domestic Product, Second Quarter 2024 (BEA)]{.link}](https://www.bea.gov/sites/default/files/2024-08/gdp2q24-2nd.pdf)


# More dimensions {background-color="#62259D"}
 

## More dimensions

<br>

Since its adoption in the mid-1930s, [GDP]{.note} has become the official [barometer]{.hi-slate} of [living standards]{.orange} and [business cycles]{.blue}.

. . .

Most importantly, it is one of the main indicators for formulating *national* and *international* [policies]{.hi-blue}.


. . .

<br>

  - Does that sound correct, considering a [multidimensional]{.note} approach?


. . .

<br>

🔗 [[Robert Kennedy on GDP (1968)]{.link}](https://www.youtube.com/watch?v=3FAmr1la6w0)

## More dimensions

<br>

GDP was [never]{.hi-slate} intended to measure *welfare* or *well-being*.

. . .

<br>

That being said, what are [examples]{.hi-red} of

. . .

<br>

  - Economic activities that [decrease]{.note} well-being, but [increase]{.note} GDP?
  
. . .

  - Economic activities that [increase]{.note} well-being, but [decrease]{.note} GDP?


## Which leads us to...




# Next time: Structure of the U.S. economy {background-color="#62259D"}