---
title: "Inflation & Central Banks"
subtitle: "Principles of Macroeconomics // Fall 2024"
institute: "marcio.santetti@emerson.edu"
format: 
  clean-revealjs:
    self-contained: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Prof. Santetti
---
  
# Readings {background-color="#62259D"}
  

  
## Readings
  
<br>
  
**Required readings**:
  
- [Macroeconomics in Context]{.note}, 4th ed.
  - Chapter 11, sections 1&mdash;2.


  

## Words of the day

<br>

- Money functions;
- Central Banks;
- Open Market Operations;
- Federal Funds Rate.


# Inflation & money {background-color="#62259D"}


## Inflation & money

<br>

As we have seen previously, one of the main [problems]{.hi} caused by inflation is that it deteriorates the [value of money]{.hi-green}.

. . .

  - In particular, money loses its [store of value]{.note} property.
  
. . .

<br>

Time to dig deeper into [money]{.hi-green} and its role in the (macro)economy.


# Roles of money {background-color="#62259D"}

## Roles of money

<br>

[Money]{.hi-green} exists in many different [forms]{.note}.

. . .

  - Cash, bank accounts, and electronic payment systems, for example.
  
. . .

<br>

In more general terms, [money]{.hi-green} is *anything* that satisfies [three specific roles]{.note}:

. . .

  1. [Medium of exchange]{.note};
  
  2. [Store of value]{.note};
  
  3. [Unit of account]{.note}.
  



## Roles of money


[[[1] Medium of exchange:]{.note}]{.bg-grey}
  
  - The accepted [token]{.hi} for sales and purchases.
  - Avoids the "[double coincidence of wants]{.note}" problem.


. . .


[[[2] Store of value:]{.note}]{.bg-grey}

  - A way of [holding wealth]{.hi-blue}.
  - The most [liquid]{.note} asset.


. . .


[[[3] Unit of account:]{.note}]{.bg-grey}

  - Monetary units define the [value]{.hi-pink} of goods and services.


## Roles of money



<br><br><br>

  - What makes us [believe]{.note} that [money]{.hi-green} is [money]{.hi-green}?



# How money is created {background-color="#62259D"}


## How money is created

. . .

<br>

When it comes to money [creation]{.hi-pink}, we may distinguish between:



  - Money [production]{.note} and [printing]{.note};
  
  - Money creation through [deposits.]{.note}

. . .

<br>

The [banking system]{.hi-grey}:

  - [Fractional]{.note} reserve system;
  
  - [Required]{.note} reserves;
  
  - [Excess]{.note} reserves.



# Central Banks {background-color="#62259D"}

## Central Banks

<br>

> *"A central bank is responsible for issuing money, conducting monetary policy, maintaining currency stability and overseeing the nation’s banking system, while acting as a lender of last resort."* (Reardon et al., 2018)

. . .

<br>

  - &#128279; [[The bank panic of 1907]{.link}](https://teachdemocracy.org/images/pdf/jpmorgan.pdf)
  
. . .

<br>

  - &#128279; [[The U.S. Federal Reserve Act of 1913]{.link}](https://www.federalreserve.gov/aboutthefed/fract.htm)
  

## Central Banks


:::: {.columns .incremental}

::: {.column}

[[Structure:]{.note}]{.bg-grey}

  - Board of [7]{.note} governors;
  - Non-renewable [14]{.note}-year terms;
  - [4]{.note}-year term chair;
  - Based in Washington, DC.


:::


::: {.column .fragment}


- Twelve [Regional]{.note} Federal Reserve Banks:

  - Atlanta
  - Boston
  - Chicago
  - Cleveland
  - Dallas
  - Kansas City
  - Minneapolis
  - New York
  - Philadelphia
  - Richmond
  - St. Louis
  - San Francisco

:::

::::



## Central Banks

<br>


[[Dual mandate:]{.note}]{.bg-grey}

<br>

. . .

  - Maximum [employment]{.note};
  - Stable [prices]{.note}.
  
. . .

<br>

These two objectives guide the Fed's [monetary policy]{.note}.

# Monetary policy {background-color="#62259D"}

## Monetary policy

<br>

Central Banks play an [active]{.note} role in the macroeconomy through [monetary policy]{.hi-purple}.

. . .

<br>

> [Monetary policy]{.hi-purple} involves influencing the economy through changes in the banking system's [reserves]{.hi}, thus affecting the [supply of money]{.note} and the [availability of credit]{.note}.

. . .

<br>

The [main]{.hi-pink} monetary policy tool is [targeting interest rates]{.hi-slate}.

## Monetary policy

Basically, [monetary policy]{.hi-purple} addresses [two]{.note} main problems:

. . .

  - [How much money in the economy?]{.note}
  
  - [How costly to obtain money?]{.note}
  
. . .


<br>

To these ends, the Central Bank has [three]{.hi} main [tools]{.note}:

. . .

  - [[Open Market Operations]{.link}](https://www.federalreserve.gov/monetarypolicy/openmarket.htm);
  
  - [[Discount rate]{.link}](https://www.federalreserve.gov/monetarypolicy/discountrate.htm);
  
  - [[Reserve requirements]{.link}](https://www.federalreserve.gov/monetarypolicy/reservereq.htm).
  
. . .

The [last two]{.note} are responsibility of the [Board of Governors]{.hi-pink}, while the [first]{.note} is determined by the [Federal Open Market Committee (FOMC)]{.hi-grey}.


## Monetary policy


<br><br>

The [most important]{.hi-red} of these three tools are [Open Market Operations]{.note}.

. . .

<br>

Let us use the [board]{.note} to better understand how these take place in the macroeconomy.


## Monetary policy

<br>

![[[By JW Mason]{.link}](https://jwmason.org)](chart.png){fig-align="center" width="900" height="500"}


# Next time: Inflation & reality {background-color="#62259D"}