---
title: "This course and other animals"
subtitle: "Introduction to Macroeconomics // Fall 2024"
institute: "marcio.santetti@emerson.edu"
format: 
  clean-revealjs:
    self-contained: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
author:
  - name: Prof. Santetti
---


# Welcome! {background-color="#62259D"}

## About prof. Santetti

<br><br>

  - Pronouns: *he/him/his*
  - [How long]{.note} in this gig?
  - Teaching [experience]{.note}
  - [Research]{.note} fields


## About you

<br>

. . .

Suggested topics:

  - Preferred [name/pronouns]{.note}
  - Prospective/actual [major(s)]{.note}?
  - Any [familiarity]{.note} with the subject?
  - Favorite [cereal]{.note}?
  
# Why this course matters


# Our places {background-color="#62259D"}


## Canvas

<br>

  - [**EC 210--01 Canvas**](https://canvas.emerson.edu/courses/2039584)
  - [**EC 210--02 Canvas**](https://canvas.emerson.edu/courses/2039585)



## Course website


<br>

[**Principles of Macroeconomics, Fall 2024**](https://github.com/marciosantetti/ec210-fall24/blob/main/README.md)



## Summing up

<br>

- On the [course website]{.note}, you will find [all lecture materials]{.hi-purple} and [all assignment descriptions]{.hi-green}.

. . .

<br>

- On [Canvas]{.note}, you will submit/do [all assignments]{.hi}.

    - Quizzes, Mini Projects, Fall newsletter, etc.
    - There, you can also check your [attendance]{.hi-blue}.
  
  
  

# TODO {background-color="#62259D"}

## TODO

[Two]{.hi} assignment due next Tuesday (09/10), before class:


  - *Knowing you better*;
  - *Syllabus Quiz*.

  



Find both on [Canvas]{.note}.

. . .

<br>

- Recommended podcast listening:

  - [*Rethinking the AI boom, with Daron Acemoğlu*](https://www.ft.com/content/e865a777-501a-4417-839e-dffd4b5206e7) ([The Economics Show]{.note} with Soumaya Keynes podcast)
  - Also available on Spotify, Apple podcasts, etc.


  
# Next time: Macroeconomics & well-being {background-color="#62259D"}
  
  